before_script:
  - gem install minitest -v '~> 4.7'
  - gem install rdoc
  - gem install hoe
  - gem install hoe-seattlerb
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - drbrain@segment7.net
    - evan+notify@phx.io
